name: tabler_icons_for_flutter
description: use tabler icons in flutter!
version: 0.0.1
repository: https://github.com/yenyen0318/tabler_icons_for_flutter
homepage: https://github.com/yenyen0318/tabler_icons_for_flutter

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.yen.tabler_icons_for_flutter
        pluginClass: TablerIconsForFlutterPlugin
      ios:
        pluginClass: TablerIconsForFlutterPlugin

  fonts:
    - family: tabler-icons
      fonts:
        - asset: assets/fonts/tabler-icons.ttf
          style: normal
          weight: 400

